# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tfgg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.srcs/sources_1/new/SSUB.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.srcs/sources_1/new/SSHR.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.srcs/sources_1/new/SSHL.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/SCOMP.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/MUX2x1.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.srcs/sources_1/new/SREG.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.srcs/sources_1/new/SADD.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/circuit5.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/circuit4.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/project_2/project_2.srcs/sources_1/new/SMUL.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/SUB.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/SHR.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/SHL.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/REG.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/MUL.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/COMP.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Vivado/Component_Modules/ADD.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/Circuit1.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/circuit2.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/circuit3.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/ucircuit1.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/ucircuit2.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/ucircuit3.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/mixedcircuit1.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/mixedcircuit2.v
  E:/Kevin/Documents/GitHub/keving_lsepulveda_ssoumbeyalley_dpgen/circuits/output/mixedcircuit3.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top circuit5 -part xc7a100tfgg676-1


write_checkpoint -force -noxdef circuit5.dcp

catch { report_utilization -file circuit5_utilization_synth.rpt -pb circuit5_utilization_synth.pb }
